create table event_time_slot
(
    end_time         time(6),
    start_time       time(6),
    id               bigint generated by default as identity,
    slot_description varchar(255),
    slot_title       varchar(255),
    primary key (id)
)
create table event_time_slot_students
(
    event_time_slot_id bigint not null,
    students_id        bigint not null unique,
    primary key (event_time_slot_id, students_id)
)
create table event_time_slot_teachers
(
    event_time_slot_id bigint not null,
    teachers_id        bigint not null unique,
    primary key (event_time_slot_id, teachers_id)
)
create table information_event_students_new
(
    information_event_id bigint not null,
    student_id           bigint not null unique,
    primary key (information_event_id, student_id)
)
create table information_event_teachers_new
(
    information_event_id bigint not null,
    teacher_id           bigint not null unique,
    primary key (information_event_id, teacher_id)
)
create table information_event
(
    event_type       char(1),
    room_num_desks   integer,
    room_num_seats   integer,
    id               bigint generated by default as identity,
    description      varchar(255),
    name             varchar(255),
    room_building    varchar(255),
    room_description varchar(255),
    room_level       varchar(255),
    room_room_no     varchar(255),
    primary key (id)
)
create table information_event_event_time_slots
(
    event_time_slots_id  bigint not null unique,
    information_event_id bigint not null,
    primary key (event_time_slots_id, information_event_id)
)
create table person_roles
(
    id        bigint generated by default as identity,
    person_id bigint unique,
    primary key (id)
)
create table persons
(
    date_of_birth timestamp(6) not null,
    id            bigint generated by default as identity,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    primary key (id)
)
create table student
(
    id bigint not null,
    primary key (id)
)
create table teacher
(
    id                 bigint not null,
    teacher_identifier varchar(255),
    primary key (id)
)